FROM alpine:3.9

LABEL maintainer="Jonathan Goldfarb <jgoldfar@my.fit.edu>"

RUN apk add --no-cache \
      curl \
      git \
      mercurial \
      make \
      vim \
      tar \
      perl

COPY minplus.profile .

RUN curl -L http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz -o install-tl-unx.tar.gz && \
    tar xzf install-tl-unx.tar.gz && \
    ./install-tl-*/install-tl -profile ./minplus.profile

ENTRYPOINT /bin/bash
