FROM alpine:3.9

LABEL maintainer="Jonathan Goldfarb <jgoldfar@my.fit.edu>"

RUN apk add --no-cache \
      curl \
      git \
      make \
      vim \
      sbcl

ENV MaximaPath=/opt/maxima
ENV PATH=${MaximaPath}/usr/bin:${PATH}

RUN git clone https://git.code.sf.net/p/maxima/code ${MaximaPath} && \
    cd ${MaximaPath} && \
    ./bootstrap && \
    ./configure --enable-sbcl --prefix=${MaximaPath}/usr --enable-quiet-build && \
    make install
